### ISSUE TITLE
Adjust mosquito model to observed biting rates and EIR

### ISSUE THREAD

**Issue by shainova** [shainova/malaria_interventions#15]
The mosquito model in mathematica should reflect the EIR we see in the field WITHOUT intervention. Can be based on the 2004 paper by Appaw.

Question is how to implement seasonality in the medium/low regimes. Probably can do it simply by using lower mean bittng rates but leaving the daily biting rte vector the same as in high diversity.

**Comment by shainova** [comment]
@heqixin When comparing to Kathryn's data it seems like we need to adjust the phase and amplitude as well. I guess we want to be as accurate as possible no? to then simulate the IRS?

**Comment by shainova** [comment]
@heqixin So we decided to use EIR values which are more similar to the Appaw paper ( around 10 for wet season and 1-2 for dry season) or our own data (~5 in the wet season and 3 in the dry season)??

To me it makes more sense to 10 in the high season. What do you say???

**Comment by heqixin** [comment]
Hahaha, actually our entomologist is Appawu. We can go with appawu paper
for now. The only concern might be too much drop in diversity foelr dry
season

**Comment by shainova** [comment]
@heqixin My mistake. I see now that we have EIR ~1.2 in dry season and ~19 in wet. I will change the mathematica to make the dry season around~3.5. Is that ok?

**Comment by shainova** [comment]
@heqixin My mistake. I see now that we have EIR ~1.2 in dry season and about 9 in wet. I will change the mathematica to make the dry season around 3.5. Is that ok?

**Comment by heqixin** [comment]
Sure

**Comment by shainova** [comment]
Decided on parameters in Mathematica, now need to test that seasonality produces similar results to non-seasonal systems

**Comment by shainova** [comment]
Decided to only run for high diversity. Also, a better description of the problem is now in issue #25. So closing this one.
