### ISSUE TITLE
Make a new matrix for var types in 6 surveys

### ISSUE THREAD

**Issue by shainova** [shainova/malaria_interventions#19]
Re-analyze the fasta files to produce a var-type by isolate matrix for 6 surveys, including upsA/BC for each var type.

**Comment by shainova** [comment]
@heqixin Can you do that? do we have all the data?

**Comment by shainova** [comment]
Uploaded table with var types and isolates (`S1ToS6_all_renamed_otuTable_binary.txt.zip`). Still need the list of upsA/BC

**Comment by heqixin** [comment]
classification file for each type is there in the dropbox
