### ISSUE TITLE
Adjusting temporal diversity in empirical data?

### ISSUE THREAD

**Issue by shainova** [shainova/malaria_interventions#30]
@heqixin In the previous version we rescale the values of interlayer edges to calculate the modularity. We then compare the persistence of the modules (which can range now 1-6 layers) among scenarios and the empirical data. I think this comparison is ok because the persistence of modules is a result of interlayer edges. **(do you agree?)**

By this logic we may not need to adjust the temporal diversity, as it is calculated by D*relative persistence. **What do you think???**

**Comment by heqixin** [comment]
I agree.
