### ISSUE TITLE
Persistence of modules in simulations of empirical data

### ISSUE THREAD

**Issue by shainova** [shainova/malaria_interventions#37]
Modules persist for a single layer mostly. This could be a result of:
1. Cutoff
2. Using genes instead of alleles.

Some experiments with cutoff do not seem to hold promise. Will now look at the option of using alleles.

**Comment by shainova** [comment]
Next steps:
* use alleles instead of genes
* run analysis on 001 experiments in selection, to see if whatever results we get is due to IRS

**Comment by shainova** [comment]
Trying out four options:
| Command | Description |
| --- | --- |
| git status | List all new or modified files |
| git diff | Show file differences that haven't been staged |

**Comment by shainova** [comment]
@heqixin Some updates **based on preliminary analysis (6 of 100 runs)**:

## Proportion of modules that passed S3
(i.e., `filter(birth_layer<3, death_layer>3)`). Shows that intervention has stronger effect on N+G than S.
![prob_pass_intervention](https://user-images.githubusercontent.com/3636280/50527400-b099cc00-0aad-11e9-9f1b-de93aacf4752.png)

## Module survival 
Probability that a module born in layer 1 will survive 6 layers. This really needs more data
![module survival](https://user-images.githubusercontent.com/3636280/50528003-6286c780-0ab1-11e9-9158-c36819947e2a.png)

**Comment by shainova** [comment]
Need to run analysis for option 3 on:

|exp|scenarios|PS|Comments
|---|---|---|---
002|SNG|500-599|Now running...
001|SNG|500-599|Need to copy CP sqlites for G+N then create 001 files

**Comment by shainova** [comment]
@heqixin Take a look at these interesting results. The survival analysis is the probabiliy of modules born in layer 1 to reach layer 6. For selection, the results show there is an effect of intervention, though not huge. For G and N it is somewhat the opposite. interesting... I plotted this from the perspective of experiment (001 control 002 intervention) and scenario. I wonder how this compares to empirical data, but I can only analyze that at the office.

![survival_analysis_by_exp](https://user-images.githubusercontent.com/3636280/50548885-c0362380-0c19-11e9-83fb-407bf5999a35.png)
![survival_analysis_by_scenario](https://user-images.githubusercontent.com/3636280/50548887-c0362380-0c19-11e9-9fc9-4be1d5ce8840.png)

**Comment by shainova** [comment]
@heqixin ok, here is the empirical data with alleles. Basically, the same as with genes. very strong signal!
![modules_empirical_alleles](https://user-images.githubusercontent.com/3636280/50551783-4b301180-0c4c-11e9-9f23-874ba2affb0c.png)

**Comment by heqixin** [comment]
So the intervention must be really strong

**Comment by shainova** [comment]
After much more analysis and theoretical discussion we have arrived at the final analysis (see the paper)
